<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rtg_auto_bag_compress</name>
  <version>0.1.0</version>
  <description>Record compressed PlcMsg and ExecStatusMsg event segments.</description>
  <maintainer email="wxh@example.com">wxh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rosbag2_compression</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>rtg_algorithm_interfaces</depend>
  <depend>sensor_device_interfaces</depend>

  <exec_depend>rosbag2_storage_default_plugins</exec_depend>
  <exec_depend>rosbag2_compression_zstd</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
