<?xml version="1.0"?>
<package format="3">
  <name>rtg_split_db3</name>
  <version>0.1.0</version>
  <description>Split large rosbag2 DB3 files by stationary gantry bay intervals.</description>
  <maintainer email="wxh@example.com">wxh</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>rtg_algorithm_interfaces</depend>
  <depend>sensor_device_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
